import React, { Component } from "react";
import './Heros.css';

export class Heros extends Component {
    state = {
        name: 'Guidoune',
        power: 'tu maîtrises le feu'
    };

    randomName = () => {
        const names = [
            'Guidoune',
            'Matante',
            'Câlisse',
            'Carcajou',
            'Caribou',
            'Poutine',
            'Molécule',
            'Gérard',
            'Boy',
            'Magma',
            'Fantastique',
            'Arcane',
            'Béton',
            'Congère',
            'Ampère',
            'Table',
            'Cheddar',
            'Arbre',
            'Art Contemporain',
            'Porte-manteau',
            'Caoutchouc',
            'Cure-dent',
            'Woman',
            'Fauteuil',
            'Magique',
            'Astro',
            'Dark',
            'Nerf',
            'Téléport',
            'Diplomatie',
            'Beurre',
            'Pronostic',
            'Effluve',
            'Potassium',
            'Pectine',
            'Extincteur',
            'Caméléon',
            'Mystère',
            'Câble',
            'Beyblade',
            'Vitre',
            'Porte',
            'Trottinette',
            'Post-it',
            'Moquette',
            'Lumière',
            'Pachyderme',
            'Chemise',
            'Plastique',
            'Madagascar',
            'Cascade',
            'Sopalin',
            'Pétard',
            'Info',
            'Ça alors',
            'Infini',
            'Cholestérol',
            'Fusible',
            'Siphon',
            'Harmonie',
            'Rhinocéros',
            'Gangster',
            'Hirsute',
            'Escalator',
            'GPS',
            'Prévention',
            'Frigidaire',
            'Petit four',
            'Abricot',
            'Haltère',
            'Napalm',
            'Blizzard',
            'Zodiaque',
            'Papier-bulle',
            'Télécommande',
            'Baveux',
            'Fafouin',
            'Biologique',
            'Bombe',
            'Pizza',
            'Fondue',
            'Framboise',
            'Cuisine',
            'Néon',
            'Clarinette',
            'Guitare',
            'Vapeur',
            'Rocher',
            'Québec',
            'Cristaline',
            'Parpaing',
            'Tournevis',
            'Hibou',
            'Sol',
            'Fourchette',
            'Ventilateur',
            'Littérature',
            'Edge',
            'Gallinacé',
            'Nicolas',
        ];

        const powers = [
            'tu maîtrises le feu',
            'tu maîtrises la glace',
            'tu maîtrises le coup de patoune',
            'tu maîtrises l\'électricité',
            'tu maîtrises le fromage',
            'tu peux devenir invisible dans le noir',
            'tu maîtrises le béton',
            'tu maîtrises la lave',
            'tu peux comprendre l\'art contemporain',
            'tu peux te téléporter à 1cm de distance',
            'tu connais plein de tours de magie',
            'tu maîtrises le caoutchouc',
            'tu n\'as aucun pouvoir, mais au moins ton nom est cool',
            'tu peux ravitailler en munitions NERF',
            'tu contrôles les portes-manteaux',
            'tu maîtrises le contrôle qualité des fauteuils',
            'tu sais jouer aux cartes Yu-Gi-Oh',
            'tu peux roter l\'alphabet à l\'envers',
            'tu maîtrises les cure-dents',
            'tu maîtrises les nids de poule',
            'tu maîtrises les playlists Youtube',
            'tu maîtrises les programmes TV',
            'tu connais la table périodique des éléments',
            'tu peux boire de l\'acide chlorhydrique',
            'tu maîtrises la vision diurne en pleine nuit',
            'tu contrôles les cris des enfants de tes voisins',
            'tu peux tirer des flèches avec l\'Arc de Triomphe',
            'tu maîtrises les pieds de table',
            'tu maîtrises les aiguilles de conifères',
            'tu maîtrises l\'art du DAB',
            'tu peux changer le nom de n\'importe qui en "Gérard"',
            'tu peux survivre à une chute d\'exactement 500.26m',
            'tu es immunisé aux balles toutes les 4 balles reçues',
            'tes pieds sentent vraiment très fort',
            'tu as une cape',
            'tu connais toutes les chansons de Robert Charlebois',
            'tu peux attraper n\'importe quel papillon sans filet',
            'tu peux invoquer des cacahouètes',
            'tu suintes du beurre',
            'tu peux absorber les raisins',
            'tu peux tout transformer en banane',
            'tu peux te transformer en lampe',
            'tu peux changer le parfum de n\'importe quelle boisson en "fraise"',
            'tu vois tout en beige',
            'tu ne clignes jamais des yeux',
            'tu peux liker un commentaire deux fois',
            'tu peux arrêter le temps pendant 1 seconde toutes les 24 heures',
            'tu peux lire tes propres pensées',
            'tu maîtrises les tuyaux d\'arrosage',
            'tu peux t\'auto-détruire',
            'tu sais où est Ornicar',
            'tu sais imiter le cri du tapir',
            'tu peux faire apparaître des portes',
            'tu sais lacer n\'importe quelle chaussure',
            'tu peux prédire les résultats de chaque match 30 secondes avant leur fin',
            'tu peux pousser Mémé dans les orties',
            'tu connais la capitale du Swaziland',
            'tu peux transformer l\'or en argent',
            'tu peux faire du moonwalk sur la Lune',
            'tu communiques avec les pamplemousses',
            'tu peux devenir chauve à volonté',
            'tu peux faire des super slow-motions',
            'tu obtiens la super-force pendant une seconde toutes les 48 heures',
            'tu peux séduire n\'importe quel chapeau',
            'tu peux désaturer toutes les images',
            'tu peux réciter "Guerre et Paix" de Tolstoï par coeur',
            'tu peux détecter les ordures à 10 mètres',
            'tu peux arrêter les escalators',
            'tu es capable d\'énoncer l\'angle de n\'importe quel objet',
            'tu passes seulement 10 minutes dans un magasin IKEA',
            'tu peux éternuer avec les yeux ouverts',
            'tu sens la vanille',
            'tu peux vivre jusqu\'à ta mort',
            'tu peux respirer dans l\'espace',
            'tu peux faire rire les personnes âgées',
            'tu es super edgy',
            'tu peux lancer un boomerang sans qu\'il ne revienne',
            'tu peux te transformer en David Pujadas',
            'tu connais la température de Saint-Eustache-la-Forêt',
            'tu es immunisé aux pétards',
            'toutes tes phrases finissent par "Boy"',
            'tu ne peux pas marcher sur les LEGO',
            'tu peux danser la Tektonik à n\'importe qui',
            'tu ne rigoles qu\'aux blagues nulles',
            'tu sais qui est le président du Kirghizistan',
            'tu peux endormir n\'importe quel rhinocéros',
            'tu n\'as pas besoin de Google Maps',
            'tu disparais quand les gens clignent des yeux',
            'tu peux faire apparaître des moustaches',
            'tu ne peux boire que de la Salvetat',
            'tu connais les règles du cricket',
            'tu peux respirer en dehors de l\'eau',
            'tu fais apparaître des pâtes al dente dans chaque plat',
            'tu peux transformer les canards en pintades',
            'tu peux cracher du feu avec tes aisselles',
            'tu peux parler ouzbèke pendant 30 secondes toutes les 2 heures',
            'tu peux lire l\'avenir dans les méduses',
            'tu peux écrire à la craie sur les tableaux Veleda',
            'tu maîtrises toutes les figures de style',
            'tu maîtrises les toupies',
        ];

        const randomName = Math.floor(Math.random() * 100);
        const hero = names[randomName];

        const randomPower = Math.floor(Math.random() * 100);
        const power = powers[randomPower];

        console.log(`name: ${randomName} power: ${randomPower}`)

        this.setState({ 
            name: hero,
            power: power
        });
        };

    selectHandler = (event) => {
        this.setState({ name: event.target.value })
    }

    render() {
        return (
            <div className="randomHero">
            <br />
            <br />
                <h2 font-color= 'white'>Deviens un super héros</h2>
                    <button onClick={this.randomName}>Générer un nom</button>
                    <br />
                    <br/>
                    Tu es
                <h3>{this.state.name} Man et {this.state.power} !</h3>               
            </div>
        );
    }
}
export default Heros;

