import React, { Component } from "react";
import './Heros.css';

import ShuffleText from 'react-shuffle-text';

export class Heros extends Component {
    state = {
        name: 'Guidoune',
        power: 'tu maîtrises le feu',
        enemyName: 'le docteur Doofenschmirtz',
        enemyPower: 'c\'est un professeur diabolique',

    };

    randomName = () => {
        const names = [
            'Guidoune',
            'Matante',
            'Câlisse',
            'Carcajou',
            'Caribou',
            'Poutine',
            'Molécule',
            'Gérard',
            'Boy',
            'Magma',
            'Fantastique',
            'Arcane',
            'Béton',
            'Congère',
            'Ampère',
            'Table',
            'Cheddar',
            'Arbre',
            'Art Contemporain',
            'Porte-manteau',
            'Caoutchouc',
            'Cure-dent',
            'Woman',
            'Fauteuil',
            'Magique',
            'Astro',
            'Dark',
            'Nerf',
            'Téléport',
            'Diplomatie',
            'Beurre',
            'Pronostic',
            'Effluve',
            'Potassium',
            'Pectine',
            'Extincteur',
            'Caméléon',
            'Mystère',
            'Câble',
            'Beyblade',
            'Vitre',
            'Porte',
            'Trottinette',
            'Post-it',
            'Moquette',
            'Lumière',
            'Pachyderme',
            'Chemise',
            'Plastique',
            'Madagascar',
            'Cascade',
            'Sopalin',
            'Pétard',
            'Info',
            'Ça alors',
            'Infini',
            'Cholestérol',
            'Fusible',
            'Siphon',
            'Harmonie',
            'Rhinocéros',
            'Gangster',
            'Hirsute',
            'Escalator',
            'GPS',
            'Prévention',
            'Frigidaire',
            'Petit four',
            'Abricot',
            'Haltère',
            'Napalm',
            'Blizzard',
            'Zodiaque',
            'Papier-bulle',
            'Télécommande',
            'Baveux',
            'Fafouin',
            'Biologique',
            'Bombe',
            'Pizza',
            'Fondue',
            'Framboise',
            'Cuisine',
            'Néon',
            'Clarinette',
            'Guitare',
            'Vapeur',
            'Rocher',
            'Québec',
            'Cristaline',
            'Parpaing',
            'Tournevis',
            'Hibou',
            'Sol',
            'Fourchette',
            'Ventilateur',
            'Littérature',
            'Edge',
            'Gallinacé',
            'Nicolas',
        ];

        const powers = [
            'tu maîtrises le feu',
            'tu maîtrises la glace',
            'tu maîtrises le coup de patoune',
            'tu maîtrises l\'électricité',
            'tu maîtrises le fromage',
            'tu peux devenir invisible dans le noir',
            'tu maîtrises le béton',
            'tu maîtrises la lave',
            'tu peux comprendre l\'art contemporain',
            'tu peux te téléporter à 1cm de distance',
            'tu connais plein de tours de magie',
            'tu maîtrises le caoutchouc',
            'tu n\'as aucun pouvoir, mais au moins ton nom est cool',
            'tu peux ravitailler en munitions NERF',
            'tu contrôles les portes-manteaux',
            'tu maîtrises le contrôle qualité des fauteuils',
            'tu sais jouer aux cartes Yu-Gi-Oh',
            'tu peux roter l\'alphabet à l\'envers',
            'tu maîtrises les cure-dents',
            'tu maîtrises les nids de poule',
            'tu maîtrises les playlists Youtube',
            'tu maîtrises les programmes TV',
            'tu connais la table périodique des éléments',
            'tu peux boire de l\'acide chlorhydrique',
            'tu maîtrises la vision diurne en pleine nuit',
            'tu contrôles les cris des enfants de tes voisins',
            'tu peux tirer des flèches avec l\'Arc de Triomphe',
            'tu maîtrises les pieds de table',
            'tu maîtrises les aiguilles de conifères',
            'tu maîtrises l\'art du DAB',
            'tu peux changer le nom de n\'importe qui en "Gérard"',
            'tu peux survivre à une chute d\'exactement 500.26m',
            'tu es immunisé aux balles toutes les 4 balles reçues',
            'tes pieds sentent vraiment très fort',
            'tu as une cape',
            'tu connais toutes les chansons de Robert Charlebois',
            'tu peux attraper n\'importe quel papillon sans filet',
            'tu peux invoquer des cacahouètes',
            'tu suintes du beurre',
            'tu peux absorber les raisins',
            'tu peux tout transformer en banane',
            'tu peux te transformer en lampe',
            'tu peux changer le parfum de n\'importe quelle boisson en "fraise"',
            'tu vois tout en beige',
            'tu ne clignes jamais des yeux',
            'tu peux liker un commentaire deux fois',
            'tu peux arrêter le temps pendant 1 seconde toutes les 24 heures',
            'tu peux lire tes propres pensées',
            'tu maîtrises les tuyaux d\'arrosage',
            'tu peux t\'auto-détruire',
            'tu sais où est Ornicar',
            'tu sais imiter le cri du tapir',
            'tu peux faire apparaître des portes',
            'tu sais lacer n\'importe quelle chaussure',
            'tu peux prédire les résultats de chaque match 30 secondes avant leur fin',
            'tu peux pousser Mémé dans les orties',
            'tu connais la capitale du Swaziland',
            'tu peux transformer l\'or en argent',
            'tu peux faire du moonwalk sur la Lune',
            'tu communiques avec les pamplemousses',
            'tu peux devenir chauve à volonté',
            'tu peux faire des super slow-motions',
            'tu obtiens la super-force pendant une seconde toutes les 48 heures',
            'tu peux séduire n\'importe quel chapeau',
            'tu peux désaturer toutes les images',
            'tu peux réciter "Guerre et Paix" de Tolstoï par coeur',
            'tu peux détecter les ordures à 10 mètres',
            'tu peux arrêter les escalators',
            'tu es capable d\'énoncer l\'angle de n\'importe quel objet',
            'tu passes seulement 10 minutes dans un magasin IKEA',
            'tu peux éternuer avec les yeux ouverts',
            'tu sens la vanille',
            'tu peux vivre jusqu\'à ta mort',
            'tu peux respirer dans l\'espace',
            'tu peux faire rire les personnes âgées',
            'tu es super edgy',
            'tu peux lancer un boomerang sans qu\'il ne revienne',
            'tu peux te transformer en David Pujadas',
            'tu connais la température de Saint-Eustache-la-Forêt',
            'tu es immunisé aux pétards',
            'toutes tes phrases finissent par "Boy"',
            'tu ne peux pas marcher sur les LEGO',
            'tu peux faire danser la Tektonik à n\'importe qui',
            'tu ne rigoles qu\'aux blagues nulles',
            'tu sais qui est le président du Kirghizistan',
            'tu peux endormir n\'importe quel rhinocéros',
            'tu n\'as pas besoin de Google Maps',
            'tu disparais quand les gens clignent des yeux',
            'tu peux faire apparaître des moustaches',
            'tu ne peux boire que de la Salvetat',
            'tu connais les règles du cricket',
            'tu peux respirer en dehors de l\'eau',
            'tu fais apparaître des pâtes al dente dans chaque plat',
            'tu peux transformer les canards en pintades',
            'tu peux cracher du feu avec tes aisselles',
            'tu peux parler ouzbèke pendant 30 secondes toutes les 2 heures',
            'tu peux lire l\'avenir dans les méduses',
            'tu peux écrire à la craie sur les tableaux Veleda',
            'tu maîtrises toutes les figures de style',
            'tu maîtrises les toupies',
        ];

        const enemiesName = [
            'le docteur Doofenschmirtz',
            'le professeur Pigequedal',
            'le Caméléon',
            'le Capricorne',
            'François Fillon Man',
            'une congrégation de témoins de Jéhovah',
            'Frelon Man',
            'la Sorcière de la Mort',
            'Jean-Pierre Foucault',
            'le Chimiste',
            'le Pigeon Monarque',
            'le Torréfacteur',
            'Ventilator Master',
            'la classe de CP de l\'école Sainte-Geneviève',
            'Lego Man',
            'Seto Kaiba',
            'le mec qui détruit tout à la WiiMote',
            'Fortune Master',
            'le Manchot',
            'le docteur Tartopum',
            'le guichetier de la SNCF',
            'Slowalk Man',
            'Water Man',
            'le Hibou Grand-Duc septentrional',
            'le Capitaine Krabs',
            'Kev Adams',
            'un p***** de furry',
            'Florentin',
            'toi-même',
            'le Dabber fou',
            'l\'homme-flaque d\'eau',
            'le maître-nageur de la piscine de Bolbec',
            'un magnat du pétrole texan',
            'l\'homme au pied-de-biche du T2',
            'cette guidoune de Little Mac',
            'Razorback',
            'Pied-de-table Master',
            'le Gerboulateur',
            'le professeur Pudéyep',
            'Céline Dion',
            'le PDG de EA',
            'Nicolas Fouché',
            'Yaourt Man',
            'Cigarette Man',
            'un dealer de Vache qui rit',
            'l\'homme-Roquefort',
            'un fromager',
            'l\'homme-femme',
            'une famille en vacances',
            'ton ancien professeur de maths',
            'le professeur Oh Boy',
            'David Pujadas',
            'Magic Master',
            'Fortnite Man',
            'un héros de BD franco-belge des années 50',
            'Man Man',
            'le Saucissoneur',
            'une mouche',
            'Vincent Lefebvre',
            'la girafe des ténèbres',
            'la giga-perceuse',
            'un mec qui ne se lave pas les mains',
            'un groupe de cosplayers à la Japan Expo',
            'Escargotinator',
            'le Clarinettiste',
            'le mangeur de Pringles',
            'Tidus',
            'Harold',
            'Jean-Luc Mélenchon Man',
            'l\'homme-table',
            'le professeur Stephen Hawking',
            'un parent d\'élève',
            'la meuf de chez Nachos qui ne sait pas articuler',
            'le docteur Professeur',
            'Pikachu',
            'l\'homme hipster parisien',
            'le tarif "sur place" de chez Paul',
            'un vieux monsieur chinois',
            'la taupe dans ton jardin',
            'le Nutella',
            'ce gamin insupportable qui hurle dans l\'avion',
            'Guidoune Man et ses blagues pourtant génialissimes',
            'la mauvaise haleine de ton chef',
            'la brosse à dents',
            'l\'hygiène corporelle des gens à la piscine',
            'un braconnier de feuilles de chêne',
            'Mark Zuckerberg',
            'un pêcheur qui sent le flétan',
            'un mec qui gare sa moto n\'importe comment',
            'un cultivateur d\'asperges',
            'l\'homme-amanite-tue-mouches',
            'un rugbyman nu',
            'l\'homme-pintade',
            'Vaisselle Master',
            'le Lanceur de lave-vaisselle',
            'Poire Master',
            'Negative Colissimo Man',
            'un cowboy trompettiste',
            'James de la Team Rocket',
        ];

        const enemiesPower = [
            'c\'est un professeur diabolique',
            'il connait tous les multiples de 1',
            'il fait des créneaux à la perfection',
            'il ne se lave jamais les dents',
            'ses dabs font peur aux chiens',
            'il peut se transformer en flaque d\'eau',
            'il a toujours 30 minutes de retard',
            'il déteste Keanu Reeves',
            'il ne mange que des poires',
            'il joue de la clarinette en permanence',
            'il fait apparaître des LEGO sous tes pieds',
            'il terrorise le TEOR',
            'c\'est un docteur belge',
            'ses parents ne lui ont pas appris la politesse',
            'il joue à Fortnite',
            'il remplace toutes les céréales par des mini saucissons',
            'il main Little Mac dans Smash Bros',
            'il met des DLCs partout',
            'il fais en sortent que tous le monde fassent des faute d\'ortografe',
            'il ne met jamais son nom sur ses bagages',
            'il augmente le cholestérol',
            'son rire est insupportable',
            'il contrôle une armée de mouettes',
            'il donne en permanence envie d\'éternuer',
            'il sifflote la même chanson en permanence',
            'il fait disparaître tous les rouleaux de papier-toilette',
        ];

        const randomName = Math.floor(Math.random() * 100);
        const hero = names[randomName];

        const randomPower = Math.floor(Math.random() * 100);
        const power = powers[randomPower];

        const randomEnemyName = Math.floor(Math.random() * 100);
        const enemyName = enemiesName[randomEnemyName];

        const randomEnemyPower = Math.floor(Math.random() * 19);
        const enemyPower = enemiesPower[randomEnemyPower];

        console.log(`name: ${randomName} power: ${randomPower} enemy: ${randomEnemyName}`)

        this.setState({ 
            name: hero,
            power: power,
            enemyName: enemyName,
            enemyPower: enemyPower
        });
        };

    selectHandler = (event) => {
        this.setState({ name: event.target.value })
    }

    render() {
        return (
            <React.Fragment>
            <div className="randomHero">
            <br />
            <br />
                <h2 font-color= 'white'>Deviens un super héros</h2>
                    <button onClick={this.randomName}>Générer une vie de super-héros</button>
                    <br />
                    <br/>
                    Tu es
                <h3>{this.state.name} Man et {this.state.power} !</h3>               
            </div>
            <div className="randomHero">
                <br/>
                Ton pire ennemi est...
                <h4>{this.state.enemyName} et {this.state.enemyPower} !</h4>   
                <br />          
            </div>
            </React.Fragment>
            
        );
    }
}
export default Heros;

